// <auto-generated />
using System;
using Ejercicio11.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Ejercicio11.Migrations
{
    [DbContext(typeof(VehiculosContext))]
    [Migration("20230526030750_primer_migracion")]
    partial class primer_migracion
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Ejercicio11.Models.Rueda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<short>("AltoLlanta")
                        .HasColumnType("smallint");

                    b.Property<short>("AnchoLlanta")
                        .HasColumnType("smallint");

                    b.Property<int>("PresionMaximaAire")
                        .HasColumnType("int");

                    b.Property<short>("Rodado")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.ToTable("Ruedas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AltoLlanta = (short)55,
                            AnchoLlanta = (short)245,
                            PresionMaximaAire = 35,
                            Rodado = (short)20
                        },
                        new
                        {
                            Id = 2,
                            AltoLlanta = (short)50,
                            AnchoLlanta = (short)215,
                            PresionMaximaAire = 32,
                            Rodado = (short)17
                        },
                        new
                        {
                            Id = 3,
                            AltoLlanta = (short)60,
                            AnchoLlanta = (short)265,
                            PresionMaximaAire = 35,
                            Rodado = (short)18
                        },
                        new
                        {
                            Id = 4,
                            AltoLlanta = (short)55,
                            AnchoLlanta = (short)235,
                            PresionMaximaAire = 34,
                            Rodado = (short)19
                        },
                        new
                        {
                            Id = 5,
                            AltoLlanta = (short)50,
                            AnchoLlanta = (short)245,
                            PresionMaximaAire = 36,
                            Rodado = (short)20
                        },
                        new
                        {
                            Id = 6,
                            AltoLlanta = (short)50,
                            AnchoLlanta = (short)205,
                            PresionMaximaAire = 32,
                            Rodado = (short)16
                        },
                        new
                        {
                            Id = 7,
                            AltoLlanta = (short)55,
                            AnchoLlanta = (short)265,
                            PresionMaximaAire = 35,
                            Rodado = (short)17
                        },
                        new
                        {
                            Id = 8,
                            AltoLlanta = (short)55,
                            AnchoLlanta = (short)235,
                            PresionMaximaAire = 34,
                            Rodado = (short)18
                        },
                        new
                        {
                            Id = 9,
                            AltoLlanta = (short)50,
                            AnchoLlanta = (short)215,
                            PresionMaximaAire = 32,
                            Rodado = (short)17
                        },
                        new
                        {
                            Id = 10,
                            AltoLlanta = (short)60,
                            AnchoLlanta = (short)265,
                            PresionMaximaAire = 35,
                            Rodado = (short)18
                        });
                });

            modelBuilder.Entity("Ejercicio11.Models.Vehiculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CantidadRuedas")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaLanzamiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Peso")
                        .HasColumnType("int");

                    b.Property<int>("RuedaId")
                        .HasColumnType("int");

                    b.Property<int>("TipoVehiculo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RuedaId");

                    b.ToTable("Vehiculos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CantidadRuedas = 0,
                            FechaLanzamiento = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Marca = "Ford",
                            Modelo = "Mustang",
                            Peso = 1500,
                            RuedaId = 1,
                            TipoVehiculo = 0
                        },
                        new
                        {
                            Id = 2,
                            CantidadRuedas = 0,
                            FechaLanzamiento = new DateTime(2019, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Marca = "Toyota",
                            Modelo = "Corolla",
                            Peso = 1300,
                            RuedaId = 2,
                            TipoVehiculo = 1
                        },
                        new
                        {
                            Id = 3,
                            CantidadRuedas = 0,
                            FechaLanzamiento = new DateTime(2018, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Marca = "Chevrolet",
                            Modelo = "Silverado",
                            Peso = 2000,
                            RuedaId = 3,
                            TipoVehiculo = 2
                        },
                        new
                        {
                            Id = 4,
                            CantidadRuedas = 0,
                            FechaLanzamiento = new DateTime(2021, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Marca = "Honda",
                            Modelo = "CR-V",
                            Peso = 1600,
                            RuedaId = 4,
                            TipoVehiculo = 3
                        },
                        new
                        {
                            Id = 5,
                            CantidadRuedas = 0,
                            FechaLanzamiento = new DateTime(2022, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Marca = "BMW",
                            Modelo = "i8",
                            Peso = 1700,
                            RuedaId = 5,
                            TipoVehiculo = 0
                        },
                        new
                        {
                            Id = 6,
                            CantidadRuedas = 0,
                            FechaLanzamiento = new DateTime(2019, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Marca = "Nissan",
                            Modelo = "Sentra",
                            Peso = 1400,
                            RuedaId = 6,
                            TipoVehiculo = 1
                        },
                        new
                        {
                            Id = 7,
                            CantidadRuedas = 0,
                            FechaLanzamiento = new DateTime(2017, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Marca = "Ford",
                            Modelo = "Ranger",
                            Peso = 1800,
                            RuedaId = 7,
                            TipoVehiculo = 2
                        },
                        new
                        {
                            Id = 8,
                            CantidadRuedas = 0,
                            FechaLanzamiento = new DateTime(2020, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Marca = "Toyota",
                            Modelo = "RAV4",
                            Peso = 1500,
                            RuedaId = 8,
                            TipoVehiculo = 3
                        },
                        new
                        {
                            Id = 9,
                            CantidadRuedas = 0,
                            FechaLanzamiento = new DateTime(2019, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Marca = "Chevrolet",
                            Modelo = "Cruze",
                            Peso = 1300,
                            RuedaId = 9,
                            TipoVehiculo = 1
                        },
                        new
                        {
                            Id = 10,
                            CantidadRuedas = 0,
                            FechaLanzamiento = new DateTime(2021, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Marca = "Jeep",
                            Modelo = "Wrangler",
                            Peso = 1900,
                            RuedaId = 10,
                            TipoVehiculo = 3
                        });
                });

            modelBuilder.Entity("Ejercicio11.Models.Vehiculo", b =>
                {
                    b.HasOne("Ejercicio11.Models.Rueda", "Rueda")
                        .WithMany()
                        .HasForeignKey("RuedaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
